package com.fieldservice.workorder.lifecycle;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.asm.ClassReader;
import org.springframework.asm.ClassVisitor;
import org.springframework.asm.Label;
import org.springframework.asm.MethodVisitor;
import org.springframework.asm.Opcodes;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Fitness test: no production class outside {@code com.fieldservice.workorder.lifecycle}
 * may contain a switch statement that branches on {@link com.fieldservice.domain.workorder.WorkOrderState}.
 *
 * <p>Uses Spring's repackaged ASM ({@code org.springframework.asm}) to inspect every
 * {@code .class} file under {@code com/fieldservice/}. A violation is recorded when a
 * single method both references the {@code WorkOrderState} enum <em>and</em> contains a
 * {@code TABLESWITCH} or {@code LOOKUPSWITCH} bytecode instruction.
 *
 * <p>Classes in the lifecycle package itself, synthetic {@code $SwitchMap} classes, and
 * anything under {@code test-classes} are excluded.
 */
@DisplayName("Lifecycle fitness tests")
class TransitionFitnessTest {

    private static final String STATE_INTERNAL_NAME =
            "com/fieldservice/domain/workorder/WorkOrderState";

    @Test
    @DisplayName("No production class outside workorder.lifecycle switches on WorkOrderState")
    void noSwitchOnWorkOrderStateOutsideLifecyclePackage() throws Exception {
        PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
        Resource[] resources = resolver.getResources("classpath*:com/fieldservice/**/*.class");

        List<String> violations = new ArrayList<>();

        for (Resource resource : resources) {
            String url = resource.getURL().toString();

            // Skip test-classes
            if (url.contains("test-classes") || url.contains("test-classes/")) {
                continue;
            }
            // Skip the lifecycle package itself — it is allowed to branch on state
            if (url.contains("/workorder/lifecycle/")) {
                continue;
            }
            // Skip synthetic switch-map helper classes (e.g. SomeClass$1 generated by javac)
            String fileName = url.substring(url.lastIndexOf('/') + 1);
            if (fileName.contains("$")) {
                continue;
            }

            try (InputStream is = resource.getInputStream()) {
                ClassReader reader = new ClassReader(is);
                SwitchOnStateFinder finder = new SwitchOnStateFinder(STATE_INTERNAL_NAME);
                reader.accept(finder, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
                if (finder.hasViolation()) {
                    violations.add(reader.getClassName().replace('/', '.'));
                }
            }
        }

        assertThat(violations)
                .as("Production classes outside workorder.lifecycle must not switch on WorkOrderState. "
                        + "Move branching logic into WorkOrderTransitionTable.")
                .isEmpty();
    }

    @Test
    @DisplayName("No production class outside workorder.lifecycle calls WorkOrder.setState")
    void noSetStateCallOutsideLifecyclePackage() throws Exception {
        PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
        Resource[] resources = resolver.getResources("classpath*:com/fieldservice/**/*.class");

        List<String> violations = new ArrayList<>();

        for (Resource resource : resources) {
            String url = resource.getURL().toString();
            if (url.contains("test-classes") || url.contains("test-classes/")) {
                continue;
            }
            if (url.contains("/workorder/lifecycle/")) {
                continue;
            }

            try (InputStream is = resource.getInputStream()) {
                ClassReader reader = new ClassReader(is);
                SetStateCallFinder finder = new SetStateCallFinder();
                reader.accept(finder, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
                if (finder.hasViolation()) {
                    violations.add(reader.getClassName().replace('/', '.'));
                }
            }
        }

        assertThat(violations)
                .as("Production classes outside workorder.lifecycle must not call WorkOrder.setState. "
                        + "Route all state mutations through WorkOrderTransitionService.")
                .isEmpty();
    }

    @Test
    @DisplayName("WorkOrderState has exactly 8 values — adding a state without updating the matrix fails")
    void workOrderStateHasEightValues() {
        assertThat(com.fieldservice.domain.workorder.WorkOrderState.values())
                .hasSize(8);
    }

    @Test
    @DisplayName("WorkOrderEvent has exactly 8 values — adding an event without updating the matrix fails")
    void workOrderEventHasEightValues() {
        assertThat(WorkOrderEvent.values()).hasSize(8);
    }

    // ── ASM visitors ───────────────────────────────────────────────────────────

    private static final class SetStateCallFinder extends ClassVisitor {
        private static final String WORK_ORDER_INTERNAL = "com/fieldservice/domain/workorder/WorkOrder";
        boolean violation;

        SetStateCallFinder() {
            super(Opcodes.ASM9);
        }

        boolean hasViolation() { return violation; }

        @Override
        public MethodVisitor visitMethod(int access, String name, String descriptor,
                                          String signature, String[] exceptions) {
            return new MethodVisitor(Opcodes.ASM9) {
                @Override
                public void visitMethodInsn(int opcode, String owner, String methodName,
                                             String desc, boolean isInterface) {
                    if (WORK_ORDER_INTERNAL.equals(owner)
                            && "setState".equals(methodName)) {
                        violation = true;
                    }
                }
            };
        }
    }

    private static final class SwitchOnStateFinder extends ClassVisitor {

        private final String targetInternalName;
        private boolean violation;

        SwitchOnStateFinder(String targetInternalName) {
            super(Opcodes.ASM9);
            this.targetInternalName = targetInternalName;
        }

        boolean hasViolation() {
            return violation;
        }

        @Override
        public MethodVisitor visitMethod(int access, String name, String descriptor,
                                          String signature, String[] exceptions) {
            return new MethodVisitor(Opcodes.ASM9) {
                boolean methodHasSwitch;
                boolean methodReferencesState;

                @Override
                public void visitTableSwitchInsn(int min, int max, Label dflt, Label... labels) {
                    methodHasSwitch = true;
                }

                @Override
                public void visitLookupSwitchInsn(Label dflt, int[] keys, Label[] labels) {
                    methodHasSwitch = true;
                }

                @Override
                public void visitFieldInsn(int opcode, String owner, String fieldName, String desc) {
                    if (targetInternalName.equals(owner)) {
                        methodReferencesState = true;
                    }
                }

                @Override
                public void visitMethodInsn(int opcode, String owner, String methodName,
                                             String desc, boolean isInterface) {
                    // Catch ordinal() calls on the enum (used by synthetic switch maps)
                    if (targetInternalName.equals(owner) && "ordinal".equals(methodName)) {
                        methodReferencesState = true;
                    }
                }

                @Override
                public void visitEnd() {
                    if (methodHasSwitch && methodReferencesState) {
                        violation = true;
                    }
                }
            };
        }
    }
}
