-- V1__init.sql
-- Initial schema for the field-service-api.
-- All timestamps are TIMESTAMPTZ (UTC); all PKs are UUID generated by the application.

-- ============================================================
-- Customer accounts
-- ============================================================
CREATE TABLE customer_account (
    id      UUID         NOT NULL,
    name    VARCHAR(255) NOT NULL,
    version BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer_account PRIMARY KEY (id)
);

-- ============================================================
-- Service sites
-- ============================================================
CREATE TABLE site (
    id                  UUID         NOT NULL,
    name                VARCHAR(255) NOT NULL,
    customer_account_id UUID         NOT NULL,
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_site PRIMARY KEY (id),
    CONSTRAINT fk_site_customer_account
        FOREIGN KEY (customer_account_id) REFERENCES customer_account (id)
);

CREATE INDEX idx_site_customer_account_id ON site (customer_account_id);

-- ============================================================
-- Work orders
-- ============================================================
CREATE TABLE work_order (
    id                       UUID        NOT NULL,
    reference                VARCHAR(50) NOT NULL,
    status                   VARCHAR(50) NOT NULL,
    site_id                  UUID        NOT NULL,
    assigned_technician_id   UUID,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version                  BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_work_order PRIMARY KEY (id),
    CONSTRAINT uq_work_order_reference UNIQUE (reference),
    CONSTRAINT fk_work_order_site FOREIGN KEY (site_id) REFERENCES site (id),
    CONSTRAINT chk_work_order_status CHECK (status IN (
        'OPEN', 'ASSIGNED', 'EN_ROUTE', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED'
    ))
);

CREATE INDEX idx_work_order_assigned_technician ON work_order (assigned_technician_id);
CREATE INDEX idx_work_order_site_id ON work_order (site_id);
CREATE INDEX idx_work_order_status ON work_order (status);
