-- =============================================================================
-- V34: Portal linkage tables (WO-169)
--
-- Creates portal_account_user (one CUSTOMER user → exactly one customer account)
-- and portal_invitation (invitation-based activation flow) with Envers AUD mirrors.
-- Primary keys are UUIDv7 (generated by the application layer).
--
-- contact_email_enc and contact_name_enc store AES-256-GCM ciphertext produced by
-- the platform EncryptedStringConverter (BR-23 Confidential classification).
-- The format is base64(iv).base64(ciphertext+authTag) — never plaintext.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- portal_account_user
-- Links an app_user (identity) to exactly one customer account (catalog).
-- Activation sets status = ACTIVE and stamps activated_at.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portal_account_user (
    id           UUID         NOT NULL,
    user_id      UUID         NOT NULL REFERENCES app_user(id)  ON DELETE RESTRICT,
    account_id   UUID         NOT NULL REFERENCES customer(id)  ON DELETE RESTRICT,
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    activated_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_account_user PRIMARY KEY (id),
    CONSTRAINT uq_portal_account_user_user_id UNIQUE (user_id),
    CONSTRAINT chk_portal_account_user_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED'))
);

CREATE INDEX IF NOT EXISTS idx_portal_account_user_account_id
    ON portal_account_user(account_id);

-- ---------------------------------------------------------------------------
-- portal_invitation
-- Single-use, bounded-lifetime invitation for a contact against an account.
-- token_hash stores the SHA-256(raw_token) as lowercase hex (64 chars).
-- Consumed when activated_at is set on the resulting portal_account_user row.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portal_invitation (
    id                UUID         NOT NULL,
    account_id        UUID         NOT NULL REFERENCES customer(id)  ON DELETE RESTRICT,
    contact_email_enc VARCHAR(512) NOT NULL,
    contact_name_enc  VARCHAR(512),
    token_hash        VARCHAR(64)  NOT NULL,
    expires_at        TIMESTAMPTZ  NOT NULL,
    consumed_at       TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version           INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_portal_invitation PRIMARY KEY (id),
    CONSTRAINT uq_portal_invitation_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_portal_invitation_token_hash
    ON portal_invitation(token_hash);

-- ---------------------------------------------------------------------------
-- Envers audit mirrors — required before application startup (ddl-auto=validate)
-- ---------------------------------------------------------------------------

-- portal_account_user_aud mirrors portal_account_user.
-- contact fields are NOT present (linkage fact is audited, not contact PII).
CREATE TABLE IF NOT EXISTS portal_account_user_aud (
    id           UUID        NOT NULL,
    rev          INTEGER     NOT NULL,
    revtype      SMALLINT    NOT NULL,
    created_at   TIMESTAMPTZ,
    updated_at   TIMESTAMPTZ,
    user_id      UUID,
    account_id   UUID,
    status       VARCHAR(20),
    activated_at TIMESTAMPTZ,
    CONSTRAINT pk_portal_account_user_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_portal_account_user_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_portal_account_user_aud_rev_brin
    ON portal_account_user_aud USING brin (rev);

-- portal_invitation_aud mirrors portal_invitation.
-- contact_email_enc and contact_name_enc intentionally excluded: ciphertext in
-- audit tables provides no forensic value and increases the encrypted-data surface.
CREATE TABLE IF NOT EXISTS portal_invitation_aud (
    id           UUID        NOT NULL,
    rev          INTEGER     NOT NULL,
    revtype      SMALLINT    NOT NULL,
    created_at   TIMESTAMPTZ,
    updated_at   TIMESTAMPTZ,
    account_id   UUID,
    token_hash   VARCHAR(64),
    expires_at   TIMESTAMPTZ,
    consumed_at  TIMESTAMPTZ,
    CONSTRAINT pk_portal_invitation_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_portal_invitation_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX IF NOT EXISTS idx_portal_invitation_aud_rev_brin
    ON portal_invitation_aud USING brin (rev);
