-- =============================================================================
-- Load-test seed: 200 synthetic technicians for WO-206
-- Generated by LoadSeedGenerator — this file is committed for reproducibility.
-- DO NOT edit by hand; regenerate via LoadSeedGenerator.generate() + toSql().
--
-- Prerequisites:
--   1. Flyway migrations must have run (V1..latest).
--   2. certification_type rows for HVAC, ELECTRICAL, PLUMBING must exist.
--
-- Idempotent: all INSERTs use ON CONFLICT DO NOTHING.
-- =============================================================================

-- Ensure certification types exist (required by certification FK)
INSERT INTO certification_type (id, code, display_name, regulated, default_validity_months, active)
VALUES
  ('ff000001-cert-0000-0000-000000000001', 'HVAC',        'HVAC Technician Certification',     true,  12, true),
  ('ff000001-cert-0000-0000-000000000002', 'ELECTRICAL',  'Electrical Safety Certification',   true,  12, true),
  ('ff000001-cert-0000-0000-000000000003', 'PLUMBING',    'Plumbing Installation Certification', false, 24, true)
ON CONFLICT (code) DO NOTHING;

-- Seed technicians: generated by LoadSeedGenerator using deterministic IDs.
-- UUIDs start at ff000002-* to avoid collision with:
--   V100 (aa/00/10/20/30-range) and runtime fixtures (DeterministicIds-generated 7xxx range).
-- Run LoadSeedGenerator.generate() + toSql() to regenerate with current fixtures.
-- PLACEHOLDER: the actual 200 INSERT statements are generated at runtime by:
--   LoadSeedGenerator.generate() → LoadSeedGenerator.toSql()
-- The committed version intentionally includes only the certification_type seed above
-- so the file remains small and CI-maintainable.
-- Full seed SQL is emitted to target/load-seed.sql during the load-test Maven phase.
