package com.fieldservice.platform.audit;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import org.hibernate.envers.RevisionEntity;
import org.hibernate.envers.RevisionNumber;
import org.hibernate.envers.RevisionTimestamp;

import java.io.Serializable;
import java.time.Instant;

/**
 * Custom revision entity for Hibernate Envers.
 *
 * <p>Extends the default REVINFO structure with actor attribution (user id, role),
 * request traceId, and client IP. Populated by {@link AppRevisionListener} from the
 * Spring SecurityContext and MDC set by the request filter.
 *
 * <p>The revision number is generated by the {@code revinfo_seq} PostgreSQL sequence
 * created by Flyway migration V5 so that {@code ddl-auto: validate} succeeds.
 */
@Entity
@Table(name = "REVINFO")
@RevisionEntity(AppRevisionListener.class)
public class AppRevision implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "revinfo_seq")
    @SequenceGenerator(name = "revinfo_seq", sequenceName = "revinfo_seq", allocationSize = 1)
    @RevisionNumber
    @Column(name = "REV")
    private int id;

    @RevisionTimestamp
    @Column(name = "REVTSTMP", nullable = false)
    private long timestamp;

    @Column(name = "actor_user_id", length = 255)
    private String actorUserId;

    @Column(name = "actor_role", length = 50)
    private String actorRole;

    @Column(name = "trace_id", length = 36)
    private String traceId;

    @Column(name = "client_ip", length = 45)
    private String clientIp;

    public int     getId()          { return id; }
    public long    getTimestamp()   { return timestamp; }
    public Instant getRevisionInstant() { return Instant.ofEpochMilli(timestamp); }
    public String  getActorUserId() { return actorUserId; }
    public String  getActorRole()   { return actorRole; }
    public String  getTraceId()     { return traceId; }
    public String  getClientIp()    { return clientIp; }

    void setActorUserId(String actorUserId) { this.actorUserId = actorUserId; }
    void setActorRole(String actorRole)     { this.actorRole = actorRole; }
    void setTraceId(String traceId)         { this.traceId = traceId; }
    void setClientIp(String clientIp)       { this.clientIp = clientIp; }
}
