package com.fieldservice.platform.api;

/**
 * Stable machine-readable error codes included in every API error response.
 * Clients must branch on these codes, never on message text.
 * These values are part of the public API contract and must not be renamed.
 */
public enum ErrorCode {
    VALIDATION_FAILED,
    NOT_FOUND,
    FORBIDDEN,
    ILLEGAL_TRANSITION,
    GUARD_REFUSED,
    CONFLICT,
    RATE_LIMITED,
    PROVIDER_DEGRADED,
    INTERNAL_ERROR,
    IDEMPOTENCY_CONFLICT,
    WORK_ORDER_ILLEGAL_TRANSITION,
    WORK_ORDER_GUARD_REFUSED,
    WORK_ORDER_VERSION_CONFLICT,
    AI_PROVIDER_UNAVAILABLE,
    AI_DAILY_LIMIT_REACHED,
    PAYLOAD_TOO_LARGE,
    INVALID_CREDENTIALS,
    AUTH_DEPENDENCY_UNAVAILABLE,
    UNAUTHENTICATED,
    REAUTHENTICATION_REQUIRED,
    HOLD_REASON_INVALID,
    INSUFFICIENT_STOCK,
    INVALID_STOCK_MOVEMENT,
    SLA_POLICY_UNAVAILABLE,
    PORTAL_RESOURCE_NOT_FOUND,
    RETENTION_FLOOR_VIOLATION,
    DSAR_ILLEGAL_TRANSITION,
    DSAR_GUARD_REFUSED,
    DSAR_EXPORT_NOT_READY,
    DSAR_DOWNLOAD_TOKEN_INVALID,
    CERTIFICATION_NOT_CURRENT,
    CSAT_ALREADY_ANSWERED,
    CSAT_WINDOW_EXPIRED,
    NO_GROUNDED_BASIS,
    CONCURRENT_STREAM_LIMIT_EXCEEDED,
    PHOTO_DISALLOWED_CONTENT_TYPE,
    PHOTO_CONTENT_TOO_LARGE,
    PHOTO_INTENT_NOT_FOUND,
    PHOTO_INTENT_EXPIRED,
    PHOTO_OBJECT_MISMATCH,
    PHOTO_STORAGE_UNAVAILABLE
}
