/**
 * @fileoverview Reference-data API client — customers, sites, assets, technicians,
 * skills, certification types and technician certifications.
 *
 * All functions delegate to the platform HTTP client which attaches the Bearer
 * token and normalises errors into ClientError. Every mutating call includes an
 * Idempotency-Key generated by the HTTP layer.
 *
 * @module api/refdata
 */
import { get, post, put } from './http.js'
import { toQueryString, buildPageQuery } from './pagination.js'

// ── Customers ────────────────────────────────────────────────────────────────

/**
 * @param {{ page?: number, size?: number, sort?: string, q?: string, signal?: AbortSignal }} opts
 * @returns {Promise<import('./pagination.js').PagedResponse>}
 */
export function listCustomers({ page = 0, size = 20, sort, q, signal } = {}) {
  const pq = buildPageQuery({ page, size, sort })
  const qs = toQueryString(pq) + (q ? `&q=${encodeURIComponent(q)}` : '')
  return get(`/customers?${qs}`, { signal })
}

/**
 * @param {{ name: string, reference?: string }} body
 */
export function createCustomer(body) {
  return post('/customers', { body: JSON.stringify(body) })
}

/**
 * @param {string} id
 * @param {{ name: string, reference?: string }} body
 */
export function updateCustomer(id, body) {
  return put(`/customers/${id}`, { body: JSON.stringify(body) })
}

// ── Sites ────────────────────────────────────────────────────────────────────

/**
 * @param {{ page?: number, size?: number, sort?: string, q?: string, signal?: AbortSignal }} opts
 */
export function listSites({ page = 0, size = 20, sort, q, signal } = {}) {
  const pq = buildPageQuery({ page, size, sort })
  const qs = toQueryString(pq) + (q ? `&q=${encodeURIComponent(q)}` : '')
  return get(`/sites?${qs}`, { signal })
}

/**
 * @param {{ name: string, customerId: string, addressLine1?: string, postcode?: string }} body
 */
export function createSite(body) {
  return post('/sites', { body: JSON.stringify(body) })
}

/**
 * @param {string} id
 * @param {{ name: string, customerId: string, addressLine1?: string, postcode?: string }} body
 */
export function updateSite(id, body) {
  return put(`/sites/${id}`, { body: JSON.stringify(body) })
}

// ── Assets ───────────────────────────────────────────────────────────────────

/**
 * @param {{ page?: number, size?: number, sort?: string, signal?: AbortSignal }} opts
 */
export function listAssets({ page = 0, size = 20, sort, signal } = {}) {
  const pq = buildPageQuery({ page, size, sort })
  const qs = toQueryString(pq)
  return get(`/assets?${qs}`, { signal })
}

/**
 * @param {{ serialNumber: string, model?: string, siteId: string }} body
 */
export function createAsset(body) {
  return post('/assets', { body: JSON.stringify(body) })
}

/**
 * @param {string} id
 * @param {{ serialNumber: string, model?: string, siteId: string }} body
 */
export function updateAsset(id, body) {
  return put(`/assets/${id}`, { body: JSON.stringify(body) })
}

// ── Technicians ──────────────────────────────────────────────────────────────

/**
 * @param {{ page?: number, size?: number, sort?: string, q?: string, signal?: AbortSignal }} opts
 */
export function listTechnicians({ page = 0, size = 20, sort, q, signal } = {}) {
  const pq = buildPageQuery({ page, size, sort })
  const qs = toQueryString(pq) + (q ? `&q=${encodeURIComponent(q)}` : '')
  return get(`/technicians?${qs}`, { signal })
}

/**
 * @param {{ employeeNo: string, displayName?: string, timezone?: string }} body
 */
export function createTechnician(body) {
  return post('/technicians', { body: JSON.stringify(body) })
}

/**
 * @param {string} id
 * @param {{ displayName?: string, timezone?: string }} body
 */
export function updateTechnician(id, body) {
  return put(`/technicians/${id}`, { body: JSON.stringify(body) })
}

// ── Skills ───────────────────────────────────────────────────────────────────

/**
 * @param {{ page?: number, size?: number, sort?: string, signal?: AbortSignal }} opts
 */
export function listSkills({ page = 0, size = 20, sort, signal } = {}) {
  const pq = buildPageQuery({ page, size, sort })
  return get(`/skills?${toQueryString(pq)}`, { signal })
}

/**
 * @param {{ code: string, displayName: string }} body
 */
export function createSkill(body) {
  return post('/skills', { body: JSON.stringify(body) })
}

/**
 * @param {string} id
 * @param {{ code: string, displayName: string }} body
 */
export function updateSkill(id, body) {
  return put(`/skills/${id}`, { body: JSON.stringify(body) })
}

/**
 * Batch upsert skills for a technician.
 * @param {string} technicianId
 * @param {{ items: Array<{ skillCode: string, proficiency: string, yearsExperience?: number }> }} body
 * @param {string} idempotencyKey
 */
export function upsertTechnicianSkills(technicianId, body, idempotencyKey) {
  return put(`/technicians/${technicianId}/skills`, {
    body: JSON.stringify(body),
    headers: { 'Idempotency-Key': idempotencyKey },
  })
}

// ── Certification types ──────────────────────────────────────────────────────

/**
 * @param {{ page?: number, size?: number, signal?: AbortSignal }} opts
 */
export function listCertificationTypes({ page = 0, size = 25, signal } = {}) {
  const pq = buildPageQuery({ page, size })
  return get(`/certification-types?${toQueryString(pq)}`, { signal })
}

/**
 * @param {{ code: string, displayName: string, regulated: boolean, defaultValidityMonths?: number, active: boolean }} body
 */
export function createCertificationType(body) {
  return post('/certification-types', { body: JSON.stringify(body) })
}

/**
 * @param {string} id
 * @param {{ code: string, displayName: string, regulated: boolean, defaultValidityMonths?: number, active: boolean }} body
 */
export function updateCertificationType(id, body) {
  return put(`/certification-types/${id}`, { body: JSON.stringify(body) })
}

// ── Technician certifications ────────────────────────────────────────────────

/**
 * @param {string} technicianId
 * @param {{ atDate?: string, signal?: AbortSignal }} opts
 */
export function listTechnicianCertifications(technicianId, { atDate, signal } = {}) {
  const qs = atDate ? `?atDate=${encodeURIComponent(atDate)}` : ''
  return get(`/technicians/${technicianId}/certifications${qs}`, { signal })
}

/**
 * Batch upsert certifications for a technician.
 * @param {string} technicianId
 * @param {{ items: Array<{ typeCode: string, certificateReference?: string, issuedOn: string, expiresOn?: string, issuingBody?: string }> }} body
 * @param {string} idempotencyKey
 */
export function upsertTechnicianCertifications(technicianId, body, idempotencyKey) {
  return put(`/technicians/${technicianId}/certifications`, {
    body: JSON.stringify(body),
    headers: { 'Idempotency-Key': idempotencyKey },
  })
}

/**
 * GET eligible technician IDs by required certification types.
 * @param {{ requiredTypeCodes: string[], atDate?: string, signal?: AbortSignal }} opts
 */
export function listEligibleTechnicians({ requiredTypeCodes, atDate, signal } = {}) {
  const qs = new URLSearchParams()
  requiredTypeCodes.forEach(c => qs.append('requiredTypeCodes', c))
  if (atDate) qs.set('atDate', atDate)
  return get(`/technicians/eligible?${qs.toString()}`, { signal })
}
