/**
 * API client for reference-data admin endpoints.
 *
 * Covers: Customers, Sites, Assets.
 * All GETs return the platform PagedResponse envelope.
 * Mutations accept an optional idempotencyKey (generated by caller, never
 * regenerated on retry so a retry cannot double-insert).
 *
 * @module api/referenceData
 */

import { apiFetch } from './http.js';

// ---- Customers -----------------------------------------------------------

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   contactEmail: string | null,
 *   contactPhone: string | null,
 *   address: string | null,
 *   active: boolean,
 *   createdAt: string,
 * }} Customer
 */

/**
 * @param {{ page?: number, size?: number, sort?: string, search?: string }} params
 * @returns {Promise<unknown>}
 */
export function listCustomers({ page = 0, size = 20, sort, search } = {}) {
  const qs = new URLSearchParams({ page: String(page), size: String(Math.min(size, 50)) });
  if (sort)   qs.set('sort', sort);
  if (search) qs.set('search', search);
  return apiFetch(`/customers?${qs}`);
}

/**
 * @param {{ name: string, contactEmail?: string, contactPhone?: string, address?: string }} body
 * @param {{ idempotencyKey?: string }} [opts]
 * @returns {Promise<unknown>}
 */
export function createCustomer(body, { idempotencyKey } = {}) {
  return apiFetch('/customers', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: idempotencyKey ? { 'Idempotency-Key': idempotencyKey } : {},
  });
}

/**
 * @param {string} id
 * @param {{ name?: string, contactEmail?: string, contactPhone?: string, address?: string }} body
 * @returns {Promise<unknown>}
 */
export function updateCustomer(id, body) {
  return apiFetch(`/customers/${id}`, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

/**
 * @param {string} id
 * @returns {Promise<unknown>}
 */
export function deactivateCustomer(id) {
  return apiFetch(`/customers/${id}`, { method: 'DELETE' });
}

// ---- Sites ---------------------------------------------------------------

/**
 * @typedef {{
 *   id: string,
 *   customerId: string,
 *   customerName: string,
 *   name: string,
 *   address: string | null,
 *   active: boolean,
 *   createdAt: string,
 * }} Site
 */

/**
 * @param {{ page?: number, size?: number, sort?: string, customerId?: string, search?: string }} params
 * @returns {Promise<unknown>}
 */
export function listSites({ page = 0, size = 20, sort, customerId, search } = {}) {
  const qs = new URLSearchParams({ page: String(page), size: String(Math.min(size, 50)) });
  if (sort)       qs.set('sort', sort);
  if (customerId) qs.set('customerId', customerId);
  if (search)     qs.set('search', search);
  return apiFetch(`/sites?${qs}`);
}

/**
 * @param {{ customerId: string, name: string, address?: string }} body
 * @param {{ idempotencyKey?: string }} [opts]
 * @returns {Promise<unknown>}
 */
export function createSite(body, { idempotencyKey } = {}) {
  return apiFetch('/sites', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: idempotencyKey ? { 'Idempotency-Key': idempotencyKey } : {},
  });
}

/**
 * @param {string} id
 * @param {{ name?: string, address?: string }} body
 * @returns {Promise<unknown>}
 */
export function updateSite(id, body) {
  return apiFetch(`/sites/${id}`, { method: 'PUT', body: JSON.stringify(body) });
}

/**
 * @param {string} id
 * @returns {Promise<unknown>}
 */
export function deactivateSite(id) {
  return apiFetch(`/sites/${id}`, { method: 'DELETE' });
}

// ---- Assets --------------------------------------------------------------

/**
 * @typedef {{
 *   id: string,
 *   siteId: string,
 *   siteName: string,
 *   assetType: string,
 *   serialNumber: string | null,
 *   model: string | null,
 *   active: boolean,
 *   createdAt: string,
 * }} Asset
 */

/**
 * @param {{ page?: number, size?: number, sort?: string, siteId?: string, search?: string }} params
 * @returns {Promise<unknown>}
 */
export function listAssets({ page = 0, size = 20, sort, siteId, search } = {}) {
  const qs = new URLSearchParams({ page: String(page), size: String(Math.min(size, 50)) });
  if (sort)   qs.set('sort', sort);
  if (siteId) qs.set('siteId', siteId);
  if (search) qs.set('search', search);
  return apiFetch(`/assets?${qs}`);
}

/**
 * @param {{ siteId: string, assetType: string, serialNumber?: string, model?: string }} body
 * @param {{ idempotencyKey?: string }} [opts]
 * @returns {Promise<unknown>}
 */
export function createAsset(body, { idempotencyKey } = {}) {
  return apiFetch('/assets', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: idempotencyKey ? { 'Idempotency-Key': idempotencyKey } : {},
  });
}

/**
 * @param {string} id
 * @param {{ assetType?: string, serialNumber?: string, model?: string }} body
 * @returns {Promise<unknown>}
 */
export function updateAsset(id, body) {
  return apiFetch(`/assets/${id}`, { method: 'PUT', body: JSON.stringify(body) });
}

/**
 * @param {string} id
 * @returns {Promise<unknown>}
 */
export function deactivateAsset(id) {
  return apiFetch(`/assets/${id}`, { method: 'DELETE' });
}
