package com.fieldservice.platform.crypto;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.util.Base64;

/**
 * Wires the AES-256 data-encryption key from configuration into {@link EncryptedStringConverter}.
 *
 * <p>The key is read from {@code app.encryption.data-key-base64}.  If the property is absent
 * (e.g. in unit tests that don't load application context), the no-arg constructor of
 * {@link EncryptedStringConverter} provides a deterministic test key.
 *
 * <p>In production, set {@code app.encryption.data-key-base64} to a Base64-encoded 32-byte
 * secret generated by {@code openssl rand -base64 32}.
 */
@Configuration
public class EncryptionConfiguration {

    /**
     * Provides the {@link SecretKey} used by {@link EncryptedStringConverter}.
     * Falls back to an all-zeros test key when the property is absent.
     */
    @Bean
    @ConditionalOnMissingBean(SecretKey.class)
    public SecretKey encryptionDataKey(
            @Value("${app.encryption.data-key-base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}")
            String keyBase64) {
        byte[] keyBytes = Base64.getDecoder().decode(keyBase64);
        if (keyBytes.length != 32) {
            throw new IllegalArgumentException(
                    "app.encryption.data-key-base64 must be a Base64-encoded 32-byte key; got "
                    + keyBytes.length + " bytes");
        }
        return new SecretKeySpec(keyBytes, "AES");
    }

    /**
     * Provides the {@link EncryptedStringConverter} as a Spring bean so JPA can inject
     * the data key via the constructor rather than using the no-arg fallback.
     */
    @Bean
    public EncryptedStringConverter encryptedStringConverter(SecretKey encryptionDataKey) {
        return new EncryptedStringConverter(encryptionDataKey);
    }
}
