package com.fieldservice.load;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Deterministic generator for the 200-technician load-test seed.
 *
 * <p>All output is fully synthetic and anonymized:
 * <ul>
 *   <li>No real names — technicians are named {@code Load Tech NNN}.</li>
 *   <li>No real addresses or phone numbers — positions are synthetic
 *       decimal coordinates within a bounded box representing a test region.</li>
 *   <li>No real emails — all use the {@code @loadtest.example} domain.</li>
 * </ul>
 *
 * <p><strong>Determinism guarantee</strong>: the generator is seeded with a fixed
 * long constant ({@code SEED}); calling {@link #generate()} twice on two independently
 * constructed instances produces identical output. This is verified by
 * {@link LoadSeedGeneratorTest}.
 *
 * <h3>Distribution (200 technicians)</h3>
 * <ul>
 *   <li>1–140  : active, valid {@code ELEC_DISPATCH} certification (eligible pool)</li>
 *   <li>141–165: active, expired {@code ELEC_DISPATCH} cert (excluded — certification expired)</li>
 *   <li>166–185: active, no certification (excluded — certification missing)</li>
 *   <li>186–200: inactive flag (excluded — inactive technician)</li>
 * </ul>
 *
 * <h3>Position distribution</h3>
 * Positions are distributed across a synthetic UK-adjacent bounding box
 * (lat 51.0–53.0, lon –2.0–0.2) with a small pseudo-random spread so no two
 * technicians share coordinates.
 *
 * <h3>UUID namespace</h3>
 * {@code 00000000-0000-7206-XXXX-XXXXXXXXXXXX} (WO-206 load test).
 */
public class LoadSeedGenerator {

    /** Fixed seed ensures determinism across invocations. */
    static final long SEED = 0xF1E1D_0001L;

    /** UUID namespace segment for all load-test entities. */
    static final String NS = "00000000-0000-7206";

    /** Bounding box for synthetic position distribution. */
    static final double LAT_MIN = 51.0;
    static final double LAT_MAX = 53.0;
    static final double LON_MIN = -2.0;
    static final double LON_MAX =  0.2;

    /** Mean weekly workload hours for the team (used to spread assigned WO counts). */
    static final int WORKLOAD_MEAN_HOURS = 35;

    private static final int TOTAL          = 200;
    private static final int ELIGIBLE_END   = 140;
    private static final int EXPIRED_END    = 165;
    private static final int MISSING_END    = 185;

    // ── Public API ────────────────────────────────────────────────────────────

    /**
     * Generates the full 200-technician SQL seed as an idempotent string.
     *
     * @return SQL text ready to execute against the application schema
     */
    public String generate() {
        Random rng = new Random(SEED);
        StringBuilder sql = new StringBuilder(64 * 1024);

        preamble(sql);
        insertSite(sql);
        insertCertType(sql);
        insertAppUsers(sql);
        insertTechnicians(sql, rng);
        insertValidCerts(sql);
        insertExpiredCerts(sql);
        insertPositions(sql, rng);

        sql.append("\n-- End of load-test seed (").append(TOTAL).append(" technicians)\n");
        return sql.toString();
    }

    /**
     * Returns only the app_user INSERT block (useful for incremental rebuild testing).
     */
    public List<TechnicianSpec> buildSpecs() {
        Random rng = new Random(SEED);
        List<TechnicianSpec> specs = new ArrayList<>(TOTAL);
        for (int n = 1; n <= TOTAL; n++) {
            CertStatus cert = certStatus(n);
            boolean active  = n <= MISSING_END;
            double lat = LAT_MIN + (LAT_MAX - LAT_MIN) * rng.nextDouble();
            double lon = LON_MIN + (LON_MAX - LON_MIN) * rng.nextDouble();
            specs.add(new TechnicianSpec(n, cert, active,
                    round(lat, 6), round(lon, 6)));
        }
        return specs;
    }

    // ── Generation helpers ────────────────────────────────────────────────────

    private void preamble(StringBuilder sql) {
        sql.append("-- seed-load-200-technicians.sql\n");
        sql.append("-- Generated by LoadSeedGenerator (WO-206). SYNTHETIC DATA — no PII.\n");
        sql.append("-- Idempotent: DELETE before INSERT, ON CONFLICT DO NOTHING on conflicts.\n\n");
        sql.append("-- Wipe prior load-test rows in FK-safe order\n");
        sql.append("DELETE FROM technician_position  WHERE id::text LIKE 'cc000000-0000-7206%';\n");
        sql.append("DELETE FROM technician_certification WHERE id::text LIKE 'cc000000-0000-7206%';\n");
        sql.append("DELETE FROM technician WHERE id::text LIKE 'cc000000-0000-7206%';\n");
        sql.append("DELETE FROM app_user WHERE id::text LIKE 'cc000000-0000-7206%';\n\n");
    }

    private void insertSite(StringBuilder sql) {
        sql.append("-- Load-test dispatch site\n");
        sql.append("""
            INSERT INTO site (id, name, site_code, customer_id, address_line1,
                              city, postcode, latitude, longitude, active, version)
            SELECT
                'cc000000-0000-7206-0001-000000000001'::uuid,
                'Load Test Dispatch Site', 'LT-DSP-001',
                (SELECT id FROM customer ORDER BY id LIMIT 1),
                '1 Synthetic Street', 'London', 'EC1A 9LT', 51.5074, -0.1278, true, 0
            WHERE EXISTS (SELECT 1 FROM customer LIMIT 1)
            ON CONFLICT DO NOTHING;

            """);
    }

    private void insertCertType(StringBuilder sql) {
        sql.append("-- Certification type for load tests\n");
        sql.append("""
            INSERT INTO certification_type (id, code, display_name, regulated, active, version)
            VALUES ('cc000000-0000-7206-0002-000000000001'::uuid,
                    'ELEC_DISPATCH', 'Electrical Installation (Load Test)', true, true, 0)
            ON CONFLICT DO NOTHING;

            """);
    }

    private void insertAppUsers(StringBuilder sql) {
        sql.append("-- App users for 200 load-test technicians\n");
        sql.append("INSERT INTO app_user (id, email, display_name, full_name, active, version)\n");
        sql.append("SELECT\n");
        sql.append("    ('cc000000-0000-7206-0010-' || LPAD(n::text, 12, '0'))::uuid,\n");
        sql.append("    'load-tech-' || n || '@loadtest.example',\n");
        sql.append("    'Load Tech ' || LPAD(n::text, 3, '0'),\n");
        sql.append("    'Load Technician ' || LPAD(n::text, 3, '0'),\n");
        sql.append("    true,\n");
        sql.append("    0\n");
        sql.append("FROM generate_series(1, ").append(TOTAL).append(") AS n\n");
        sql.append("ON CONFLICT DO NOTHING;\n\n");
    }

    private void insertTechnicians(StringBuilder sql, Random rng) {
        sql.append("-- Technicians: ").append(ELIGIBLE_END)
           .append(" eligible, ").append(EXPIRED_END - ELIGIBLE_END)
           .append(" expired cert, ").append(MISSING_END - EXPIRED_END)
           .append(" missing cert, ").append(TOTAL - MISSING_END).append(" inactive\n");
        sql.append("INSERT INTO technician (id, user_id, employee_code, display_name, full_name,\n");
        sql.append("                        timezone, home_base_site_id, active, version)\n");
        sql.append("SELECT\n");
        sql.append("    ('cc000000-0000-7206-0011-' || LPAD(n::text, 12, '0'))::uuid,\n");
        sql.append("    ('cc000000-0000-7206-0010-' || LPAD(n::text, 12, '0'))::uuid,\n");
        sql.append("    'LTECH-' || LPAD(n::text, 4, '0'),\n");
        sql.append("    'Load Tech ' || LPAD(n::text, 3, '0'),\n");
        sql.append("    'Load Technician ' || LPAD(n::text, 3, '0'),\n");
        sql.append("    'Europe/London',\n");
        sql.append("    'cc000000-0000-7206-0001-000000000001'::uuid,\n");
        sql.append("    CASE WHEN n <= ").append(MISSING_END).append(" THEN true ELSE false END,\n");
        sql.append("    0\n");
        sql.append("FROM generate_series(1, ").append(TOTAL).append(") AS n\n");
        sql.append("ON CONFLICT DO NOTHING;\n\n");
    }

    private void insertValidCerts(StringBuilder sql) {
        sql.append("-- Valid ELEC_DISPATCH certs (technicians 1–").append(ELIGIBLE_END).append(")\n");
        sql.append("INSERT INTO technician_certification\n");
        sql.append("    (id, technician_id, certification_code, issued_at,\n");
        sql.append("     certification_type_id, certificate_reference, issued_on, expires_on, active, version)\n");
        sql.append("SELECT\n");
        sql.append("    ('cc000000-0000-7206-0012-' || LPAD(n::text, 12, '0'))::uuid,\n");
        sql.append("    ('cc000000-0000-7206-0011-' || LPAD(n::text, 12, '0'))::uuid,\n");
        sql.append("    'ELEC_DISPATCH',\n");
        sql.append("    '2024-01-01T00:00:00Z'::timestamptz,\n");
        sql.append("    'cc000000-0000-7206-0002-000000000001'::uuid,\n");
        sql.append("    'LT-CERT-' || LPAD(n::text, 6, '0'),\n");
        sql.append("    '2024-01-01',\n");
        sql.append("    '2027-01-01',\n");  // expires in the future
        sql.append("    true,\n");
        sql.append("    0\n");
        sql.append("FROM generate_series(1, ").append(ELIGIBLE_END).append(") AS n\n");
        sql.append("ON CONFLICT DO NOTHING;\n\n");
    }

    private void insertExpiredCerts(StringBuilder sql) {
        sql.append("-- Expired ELEC_DISPATCH certs (technicians ")
           .append(ELIGIBLE_END + 1).append("–").append(EXPIRED_END).append(")\n");
        sql.append("INSERT INTO technician_certification\n");
        sql.append("    (id, technician_id, certification_code, issued_at,\n");
        sql.append("     certification_type_id, certificate_reference, issued_on, expires_on, active, version)\n");
        sql.append("SELECT\n");
        sql.append("    ('cc000000-0000-7206-0012-' || LPAD(n::text, 12, '0'))::uuid,\n");
        sql.append("    ('cc000000-0000-7206-0011-' || LPAD(n::text, 12, '0'))::uuid,\n");
        sql.append("    'ELEC_DISPATCH',\n");
        sql.append("    '2018-01-01T00:00:00Z'::timestamptz,\n");
        sql.append("    'cc000000-0000-7206-0002-000000000001'::uuid,\n");
        sql.append("    'LT-EXP-' || LPAD(n::text, 6, '0'),\n");
        sql.append("    '2018-01-01',\n");
        sql.append("    '2021-01-01',\n");  // expired 2021
        sql.append("    false,\n");
        sql.append("    0\n");
        sql.append("FROM generate_series(").append(ELIGIBLE_END + 1)
           .append(", ").append(EXPIRED_END).append(") AS n\n");
        sql.append("ON CONFLICT DO NOTHING;\n\n");
    }

    private void insertPositions(StringBuilder sql, Random rng) {
        sql.append("-- Distinct last-known positions for all 200 technicians\n");
        sql.append("-- (encrypted column stores plaintext in test env — no real GPS data)\n");
        sql.append("INSERT INTO technician_position\n");
        sql.append("    (id, technician_id, latitude, longitude, captured_at)\n");
        sql.append("VALUES\n");
        for (int n = 1; n <= TOTAL; n++) {
            double lat = LAT_MIN + (LAT_MAX - LAT_MIN) * rng.nextDouble();
            double lon = LON_MIN + (LON_MAX - LON_MIN) * rng.nextDouble();
            sql.append("    (")
               .append("'cc000000-0000-7206-0013-").append(pad12(n)).append("'::uuid, ")
               .append("'cc000000-0000-7206-0011-").append(pad12(n)).append("'::uuid, ")
               .append("'").append(round(lat, 6)).append("', ")
               .append("'").append(round(lon, 6)).append("', ")
               .append("NOW() - INTERVAL '").append(n % 30).append(" minutes')");
            if (n < TOTAL) sql.append(",\n");
        }
        sql.append("\nON CONFLICT DO NOTHING;\n");
    }

    // ── Static helpers ────────────────────────────────────────────────────────

    private static CertStatus certStatus(int n) {
        if (n <= ELIGIBLE_END) return CertStatus.VALID;
        if (n <= EXPIRED_END)  return CertStatus.EXPIRED;
        if (n <= MISSING_END)  return CertStatus.MISSING;
        return CertStatus.MISSING;
    }

    private static String pad12(int n) {
        return String.format("%012d", n);
    }

    private static double round(double val, int places) {
        return new BigDecimal(val).setScale(places, RoundingMode.HALF_UP).doubleValue();
    }

    // ── Value types ───────────────────────────────────────────────────────────

    public enum CertStatus { VALID, EXPIRED, MISSING }

    public record TechnicianSpec(
            int        index,
            CertStatus certStatus,
            boolean    active,
            double     latitude,
            double     longitude
    ) {}
}
