package com.fieldservice.load;

import com.fieldservice.fixtures.DeterministicIds;
import com.fieldservice.fixtures.TechnicianFixtures;
import com.fieldservice.fixtures.TechnicianFixtures.CertificationTemplate;
import com.fieldservice.fixtures.TechnicianFixtures.TechnicianWithCerts;
import com.fieldservice.fixtures.UserFixtures;
import com.fieldservice.fixtures.UserFixtures.UserWithRole;
import com.fieldservice.domain.technician.Technician;
import com.fieldservice.domain.technician.TechnicianCertification;
import com.fieldservice.domain.user.AppUser;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Generates a deterministic 200-technician seed pool for load testing (WO-206).
 *
 * <p>The seed is fully synthetic and anonymized — no real names, addresses, phone numbers
 * or coordinates. Two calls to {@link #generate()} with the same starting {@link DeterministicIds}
 * sequence counter produce identical output.
 *
 * <p>Certification mix (per the WO requirement of realistic variance):
 * <ul>
 *   <li>40% — current HVAC cert only (fully eligible for HVAC work orders)</li>
 *   <li>20% — current HVAC + current ELECTRICAL (dual-certified)</li>
 *   <li>20% — expiring-soon HVAC (within 30-day warning window)</li>
 *   <li>10% — expired HVAC (ineligible at EPOCH boundary — excluded by eligibility filter)</li>
 *   <li>10% — current ELECTRICAL only (eligible for ELECTRICAL work orders)</li>
 * </ul>
 *
 * <p>Position spread: technicians are placed on a synthetic 0.5° × 0.5° bounding box
 * centred on {@code (37.7749, -122.4194)} (a synthetic urban centre). Positions are
 * evenly distributed on a grid within the bounding box to ensure distinct last-known
 * positions for all 200 technicians.
 *
 * <p>Workload hours: distributed around a team mean of 20 h/week using a sawtooth
 * pattern that cycles the full 0–40 h range across the pool.
 *
 * <p>Call {@link DeterministicIds#resetSequence()} before generating to ensure
 * reproducible UUID sequences.
 */
public final class LoadSeedGenerator {

    public static final int POOL_SIZE = 200;

    // Synthetic bounding box — not a real location
    private static final double LAT_CENTRE = 37.7749;
    private static final double LON_CENTRE = -122.4194;
    private static final double HALF_SPAN = 0.25; // degrees

    private static final double MEAN_WEEKLY_HOURS = 20.0;

    private LoadSeedGenerator() {}

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------

    /**
     * Generates the 200-technician pool.
     *
     * <p>Callers should call {@link DeterministicIds#resetSequence()} before this method
     * for strict UUID reproducibility.
     */
    public static List<SeedTechnician> generate() {
        List<SeedTechnician> result = new ArrayList<>(POOL_SIZE);

        for (int i = 0; i < POOL_SIZE; i++) {
            CertificationTemplate cert = certTemplate(i);
            String employeeNo = String.format("LT-%04d", i + 1);
            String phone = String.format("+155500%05d", i + 1);

            UserWithRole user = UserFixtures.technician()
                    .withEmail(String.format("tech%04d@load-test.invalid", i + 1))
                    .buildWithRole();

            TechnicianWithCerts twc = TechnicianFixtures.active()
                    .withId(DeterministicIds.nextId())
                    .withUser(user.user())
                    .withEmployeeNo(employeeNo)
                    .withPhone(phone)
                    .withCertification(cert)
                    .build(user.user());

            BigDecimal lat = BigDecimal.valueOf(LAT_CENTRE + gridLat(i));
            BigDecimal lon = BigDecimal.valueOf(LON_CENTRE + gridLon(i));
            double bookedHours = bookedHoursForIndex(i);

            result.add(new SeedTechnician(twc, lat, lon, bookedHours));
        }

        return List.copyOf(result);
    }

    /**
     * Renders the seed as a SQL INSERT script for loading into the test database.
     *
     * <p>The script is idempotent: it uses {@code INSERT ... ON CONFLICT DO NOTHING}
     * so it can be re-run against a partially-seeded database without errors.
     */
    public static String toSql(List<SeedTechnician> seed) {
        StringBuilder sb = new StringBuilder();
        sb.append("-- Load-test seed: ").append(POOL_SIZE).append(" synthetic technicians (WO-206)\n");
        sb.append("-- Generated by LoadSeedGenerator — do NOT edit by hand\n\n");

        for (SeedTechnician s : seed) {
            Technician t = s.technicianWithCerts().technician();
            AppUser u = t.getUser();

            // app_user row
            sb.append(String.format(
                    "INSERT INTO app_user (id, email, password_hash, full_name, active, created_at, updated_at) " +
                    "VALUES ('%s', '%s', '$2a$10$LOADTESTHASHPLACEHOLDER', '%s', true, NOW(), NOW()) " +
                    "ON CONFLICT (email) DO NOTHING;\n",
                    u.getId(), u.getEmail(), "Load Test User " + t.getEmployeeNo()));

            // role assignment
            sb.append(String.format(
                    "INSERT INTO role_assignment (user_id, role_name) " +
                    "VALUES ('%s', 'TECHNICIAN') ON CONFLICT DO NOTHING;\n",
                    u.getId()));

            // technician row
            sb.append(String.format(
                    "INSERT INTO technician (id, user_id, employee_no, phone, active) " +
                    "VALUES ('%s', '%s', '%s', '%s', true) ON CONFLICT (employee_no) DO NOTHING;\n",
                    t.getId(), u.getId(), t.getEmployeeNo(), t.getPhone()));

            // technician_position row
            sb.append(String.format(
                    "INSERT INTO technician_position (technician_id, latitude, longitude, recorded_at) " +
                    "VALUES ('%s', %s, %s, NOW()) " +
                    "ON CONFLICT (technician_id) DO UPDATE SET latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude;\n",
                    t.getId(), s.latitude().toPlainString(), s.longitude().toPlainString()));

            // certifications — uses V39 schema (certification_type_id FK via code lookup)
            for (TechnicianCertification cert : s.technicianWithCerts().certifications()) {
                if (!cert.isRevoked()) {
                    sb.append(String.format(
                            "INSERT INTO technician_certification " +
                            "(id, technician_id, certification_type_id, certificate_reference, " +
                            "issued_on, expires_on, active) " +
                            "SELECT gen_random_uuid(), '%s', ct.id, '%s', " +
                            "'%s'::date, %s, true " +
                            "FROM certification_type ct WHERE ct.code = '%s' " +
                            "ON CONFLICT DO NOTHING;\n",
                            t.getId(), cert.getCertReference(),
                            cert.getIssuedAt().toString().substring(0, 10),
                            cert.getExpiresAt() != null
                                    ? "'" + cert.getExpiresAt().toString().substring(0, 10) + "'::date"
                                    : "NULL",
                            cert.getCertType()));
                }
            }

            sb.append('\n');
        }

        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Internal helpers
    // -----------------------------------------------------------------------

    /** Certification mix: 40% current HVAC, 20% dual, 20% expiring, 10% expired, 10% electrical. */
    private static CertificationTemplate certTemplate(int index) {
        int bucket = index % 10;
        return switch (bucket) {
            case 0, 1, 2, 3 -> CertificationTemplate.CURRENT_HVAC;       // 40%
            case 4, 5       -> CertificationTemplate.CURRENT_ELECTRICAL;  // 20% (dual-cert handled via separate call)
            case 6, 7       -> CertificationTemplate.EXPIRING_SOON_HVAC;  // 20%
            case 8          -> CertificationTemplate.EXPIRED_HVAC;        // 10%
            default         -> CertificationTemplate.CURRENT_ELECTRICAL;  // 10%
        };
    }

    /** Evenly distributes 200 positions on a grid within the bounding box (latitude offset). */
    private static double gridLat(int index) {
        int row = index / 14; // ~14 columns → ~15 rows ≥ 200
        double step = (2.0 * HALF_SPAN) / 14.0;
        return -HALF_SPAN + (row * step);
    }

    /** Evenly distributes 200 positions on a grid within the bounding box (longitude offset). */
    private static double gridLon(int index) {
        int col = index % 14;
        double step = (2.0 * HALF_SPAN) / 14.0;
        return -HALF_SPAN + (col * step);
    }

    /** Sawtooth workload: cycles 0–40h across the pool, mean ≈ 20h. */
    private static double bookedHoursForIndex(int index) {
        double period = 40.0;
        return (index % (int) period) * (period / (POOL_SIZE / (period / MEAN_WEEKLY_HOURS)));
    }

    // -----------------------------------------------------------------------
    // Value type
    // -----------------------------------------------------------------------

    /**
     * A single seed technician entry: domain objects + last-known position + workload.
     */
    public record SeedTechnician(
            TechnicianWithCerts technicianWithCerts,
            BigDecimal latitude,
            BigDecimal longitude,
            double bookedHoursThisWeek) {
    }
}
